###
GET https://eshop-clothings.herokuapp.com/api/product HTTP/1.1

###
POST https://eshop-clothings.herokuapp.com/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "wahedm@gmail9.com",
    "password": "1234579444"
}


###
POST https://eshop-clothings.herokuapp.com/api/user/register HTTP/1.1
content-type: application/json

{
    "email": "wahedm@gmail9.com",
    "password": "1234579444",
    "name":"wahed m",
    "phoneNumber":"09182471500"
}
