export const FETCH_ONE_PRODUCT_REQUEST = "FETCH_ONE_PRODUCT_REQUEST";
export const FETCH_ONE_PRODUCT_SUCCESS = "FETCH_ONE_PRODUCT_SUCCESS";
export const FETCH_ONE_PRODUCT_FAILURE = "FETCH_ONE_PRODUCT_FAILURE";
