import bcrypt from "bcryptjs";

export const products = [
  {
    id: 1,
    name: "Nike Dri-FIT Trail T-shirt",
    price: "35",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_dri-fit_trail_t-shirt_w2h3.jpg",
    category: "men",
    size: "S",
    color: "skyblue",
  },
  {
    id: 2,
    name: "Nike Dri-FIT Training T-shirt",
    price: "85",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_dri-fit_training_t-shirt_fh89.jpg",
    category: "men",
    size: "L",
    color: "blue",
  },
  {
    id: 3,
    name: "Nike Pro Dri-FIT Short-Sleeve Top",
    price: "35",
    discount: "",
    offPrice: "",
    image:
      "https://s6.uupload.ir/files/nike_pro_dri-fit_short-sleeve_top_kpm7.jpg",
    category: "men",
    size: "M",
    color: "green",
  },
  {
    id: 4,
    name: "Nike Sportswear Tech Fleece Wash Shorts",
    price: "85",
    discount: "",
    offPrice: "",
    image:
      "https://s6.uupload.ir/files/nike_sportswear_tech_fleece_wash_shorts_g59l.jpg",
    category: "men",
    size: "XS",
    color: "blue",
  },
  {
    id: 5,
    name: "Nike Sportswear Essential Sweater",
    price: "65",
    discount: "",
    offPrice: "36.97",
    image: "https://s6.uupload.ir/files/nike_sportswear_essentials_8nry.jpg",
    category: "women",
    size: "XL",
    color: "red",
  },
  {
    id: 6,
    name: "Nike Bliss Luxe Pants",
    price: "100",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_bliss_luxe_p1tm.jpg",
    category: "women",
    size: "L",
    color: "black",
  },
  {
    id: 7,
    name: "Nike Dri-FIT Swoosh Bras",
    price: "60",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_dri-fit_swoosh_3t1b.jpg",
    category: "women",
    size: "S",
    color: "blue",
  },
  {
    id: 8,
    name: "Nike Dri-FIT Top",
    price: "35",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_dri-fit_2xrz.jpg",
    category: "women",
    size: "M",
    color: "pink",
  },
  {
    id: 9,
    name: "Nike Sportswear Gym Vintage",
    price: "35",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_sportswear_gym_vintage_xrs5.jpg",
    category: "women",
    size: "XL",
    color: "gray",
  },
  {
    id: 10,
    name: "Nike Air Max 270 Shoes",
    price: "130",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_air_max_270_shoes_rdwo.jpg",
    category: "shoes",
    size: "",
    color: "black",
  },
  {
    id: 11,
    name: "Nike Sportswear Uphoria Sweater",
    price: "80",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike-sportswear-uphoria_g9r0.jpg",
    category: "women",
    size: "S",
    color: "green",
  },
  {
    id: 12,
    name: "Nike Color Block Swimming Clothes",
    price: "52",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_color_block_6axc.jpg",
    category: "women",
    size: "M",
    color: "black",
  },
  {
    id: 13,
    name: "NikeCourt Dri-FIT Victory Skirt",
    price: "50",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nikecourt-dri-fit-victory_u8my.jpg",
    category: "women",
    size: "L",
    color: "turqouise",
  },
  {
    id: 14,
    name: "Nike Pro Dri-FIT Flex Training Shorts",
    price: "65",
    discount: "",
    offPrice: "",
    image:
      "https://s6.uupload.ir/files/nike_pro_dri-fit_flex_training_shorts_ytw1.jpg",
    category: "men",
    size: "M",
    color: "green",
  },
  {
    id: 15,
    name: "Nike Therma Training Hoodie",
    price: "69",
    discount: "",
    offPrice: "36.97",
    image: "https://s6.uupload.ir/files/nike-therma-training-hoodie_nvc4.jpg",
    category: "men",
    size: "M",
    color: "blue",
  },
  {
    id: 16,
    name: "Nike Therma Training Pants",
    price: "55",
    discount: "",
    offPrice: "33.97",
    image: "https://s6.uupload.ir/files/nike-therma-training-pants_4qq2.jpg",
    category: "men",
    size: "XL",
    color: "gray",
  },
  {
    id: 17,
    name: "Air Jordan 1 Mid Shoes",
    price: "100",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/air-jordan-1-mid-shoes_vk2z.jpg",
    category: "shoes",
    size: "",
    color: "blue",
  },
  {
    id: 18,
    name: "Nike Dri-FIT Ultra Stretch Micro Trunks",
    price: "45",
    discount: "",
    offPrice: "36.97",
    image:
      "https://s6.uupload.ir/files/nike_dri-fit_ultra_stretch_micro_trunks_eloz.jpg",
    category: "men",
    size: "L",
    color: "",
  },
  {
    id: 19,
    name: "Nike Sportswear Tech Fleece Pants",
    price: "100",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_sportswear_tech_fleece_a8ws.jpg",
    category: "women",
    size: "M",
    color: "gray",
  },
  {
    id: 20,
    name: "NikeCourt Dri-FIT Pants",
    price: "85",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nikecourt-dri-fit_msrr.jpg",
    category: "women",
    size: "S",
    color: "green",
  },
  {
    id: 21,
    name: "Nike Dri-FIT Alate Coverage Bras",
    price: "50",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_dri-fit_alate_coverage_w6m2.jpg",
    category: "women",
    size: "M",
    color: "white",
  },
  {
    id: 22,
    name: "Nike Dri-FIT One Luxe Top",
    price: "52",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_dri-fit_one_luxe_3xu.jpg",
    category: "women",
    size: "XL",
    color: "blue",
  },
  {
    id: 23,
    name: "Nike Tempo Shorts",
    price: "30",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike-tempo_okji.jpg",
    category: "women",
    size: "XXL",
    color: "pink",
  },
  {
    id: 24,
    name: "Nike Dri-FIT Club Golf Skirt",
    price: "75",
    discount: "",
    offPrice: "67.97",
    image: "https://s6.uupload.ir/files/nike_dri-fit_club_7zf4.jpg",
    category: "women",
    size: "S",
    color: "blue",
  },

  {
    id: 25,
    name: "NikeCourt Dri-FIT Victory Tennis Skirt ",
    price: "60",
    discount: "",
    offPrice: "48.97",
    image:
      "https://s6.uupload.ir/files/nikecourt-dri-fit-victory-skirt_2a4n.jpg",
    category: "women",
    size: "L",
    color: "gray",
  },
  {
    id: 26,
    name: "Jordan Essentials Mesh Shorts",
    price: "55",
    discount: "",
    offPrice: "44.97",
    image: "https://s6.uupload.ir/files/jordan_essentials_mesh_shorts_yny.jpg",
    category: "men",
    size: "L",
    color: "green",
  },
  {
    id: 27,
    name: "Nike Sportswear Club Fleece Sweater",
    price: "50",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_sportswear_club_fleece_py5y.jpg",
    category: "men",
    size: "M",
    color: "red",
  },
  {
    id: 28,
    name: "Nike Sportswear Club Fleece Joggers",
    price: "55",
    discount: "",
    offPrice: "",
    image:
      "https://s6.uupload.ir/files/nike_sportswear_club_fleece_joggers_agk7.jpg",
    category: "men",
    size: "L",
    color: "blue",
  },
  {
    id: 29,
    name: "Nike Dri-FIT ReLuxe Underwear",
    price: "40",
    discount: "",
    offPrice: "",
    image:
      "https://s6.uupload.ir/files/nike_dri-fit_reluxe_boxer_underwear_tpa1.jpg",
    category: "men",
    size: "M",
    color: "gray",
  },
  {
    id: 30,
    name: "Air Jordan 5 Retro Shoes ",
    price: "150",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/air_jordan_5_retro_shoes_2rnd.jpg",
    category: "shoes",
    size: "",
    color: "gray",
  },
  {
    id: 31,
    name: "Nike Dri-FIT Epic Luxe Pants",
    price: "110",
    discount: "",
    offPrice: "88.97",
    image: "https://s6.uupload.ir/files/nike_dri-fit_epic_luxe_2g61.jpg",
    category: "women",
    size: "XS",
    color: "skyblue",
  },
  {
    id: 32,
    name: "Nike Epic Luxe Pants",
    price: "90",
    discount: "",
    offPrice: "81.97",
    image: "https://s6.uupload.ir/files/nike_epic_luxe_8era.jpg",
    category: "women",
    size: "XL",
    color: "orange",
  },
  {
    id: 33,
    name: "Nike Air Dri-FIT Swoosh",
    price: "45",
    discount: "",
    offPrice: "30.97",
    image: "https://s6.uupload.ir/files/nike_air_dri-fit_swoosh_a2kr.jpg",
    category: "women",
    size: "M",
    color: "purple",
  },
  {
    id: 34,
    name: "Nike Yoga Luxe Tops",
    price: "55",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike-yoga-luxe_unus.jpg",
    category: "women",
    size: "XL",
    color: "yellow",
  },
  {
    id: 35,
    name: "Nike Sportswear Swoosh Sweater",
    price: "65",
    discount: "",
    offPrice: "39.97",
    image: "https://s6.uupload.ir/files/nike_sportswear_swoosh_bsgq.jpg",
    category: "women",
    size: "M",
    color: "orange",
  },
  {
    id: 36,
    name: "Nike Adventure Swimming",
    price: "54",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_adventure_18dv.jpg",
    category: "women",
    size: "XL",
    color: "red",
  },
  {
    id: 37,
    name: "Nike Club Skirt Golf Skirt",
    price: "70",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_club_skirt_hupw.jpg",
    category: "women",
    size: "L",
    color: "blue",
  },
  {
    id: 38,
    name: "Nike One Pants",
    price: "50",
    discount: "",
    offPrice: "",
    image: "https://s6.uupload.ir/files/nike_one_iha.jpg",
    category: "women",
    size: "S",
    color: "skyblue",
  },
  {
    id: 39,
    name: "Nike One Luxe Pants",
    price: "90",
    discount: "",
    offPrice: "54.97",
    image: "https://s6.uupload.ir/files/nike_one_luxe_8yna.jpg",
    category: "women",
    size: "M",
    color: "blue",
  },
  {
    id: 40,
    name: "Nike Yoga Dri-FIT Indy Bras",
    price: "45",
    discount: "",
    offPrice: "27.97",
    image: "https://s6.uupload.ir/files/nike-yoga-dri-fit-indy_gooi.jpg",
    category: "women",
    size: "L",
    color: "blue",
  },
];

export const users = [
  {
    name: "Saheb mohamadi",
    email: "saheb.ex@gmail.com",
    password: bcrypt.hashSync("12345", 8),
    phoneNumber: "09180000000",
    isAdmin: true,
  },
  {
    name: "John",
    email: "user@example.com",
    password: bcrypt.hashSync("1234", 8),
    isAdmin: false,
    phoneNumber: "09181230000",
  },
];

export const cart = [];
