import bcrypt from "bcryptjs";

export const products = [
  {
    id: 1,
    name: "Nike Dri-FIT Trail T-shirt",
    price: 35,
    offPrice: "",
    image: "https://postimg.cc/xcmSccSK",
    category: "Men",
    color: "skyblue",
  },
  {
    id: 2,
    name: "Nike Dri-FIT Training T-shirt",
    price: 85,
    offPrice: "",
    image: "https://postimg.cc/tstQNwJJ",
    category: "Men",
    color: "blue",
  },
  {
    id: 3,
    name: "Nike Pro Dri-FIT Short-Sleeve T-shirt",
    price: 35,
    offPrice: "",
    image: "https://postimg.cc/XZ4ZsRgz",
    category: "Men",
    color: "green",
  },
  {
    id: 4,
    name: "Nike Sportswear Tech Fleece Wash Shorts",
    price: 85,
    offPrice: "",
    image: "https://postimg.cc/DmLTzSh1",
    category: "Men",
    color: "blue",
  },
  {
    id: 5,
    name: "Nike Sportswear Essential Sweater",
    price: 65,
    offPrice: "36.97",
    image: "https://postimg.cc/TKGYxrWy",
    category: "Women",
    color: "red",
  },
  {
    id: 6,
    name: "Nike Bliss Luxe Pants",
    price: 100,
    offPrice: "",
    image: "https://postimg.cc/4KDdHjSd",
    category: "Women",
    color: "black",
  },
  {
    id: 7,
    name: "Nike Dri-FIT Swoosh Bras",
    price: 60,
    offPrice: "",
    image: "https://postimg.cc/v1bMRMk5",
    category: "Women",
    color: "blue",
  },
  {
    id: 8,
    name: "Nike Dri-FIT Top",
    price: 35,
    offPrice: "",
    image: "https://postimg.cc/Fd62KQWW",
    category: "Women",
    color: "pink",
  },
  {
    id: 9,
    name: "Nike Sportswear Gym Vintage",
    price: 35,
    offPrice: "",
    image: "https://postimg.cc/XrQ30tbh",
    category: "Women",
    color: "gray",
  },
  {
    id: 10,
    name: "Nike Air Max 270 Shoes",
    price: 130,
    offPrice: "",
    image: "https://postimg.cc/18z4kGF9",
    category: "Shoes",
    color: "black",
  },
  {
    id: 11,
    name: "Nike Sportswear Uphoria Sweater",
    price: 80,
    offPrice: "",
    image: "https://postimg.cc/6TdkXFV0",
    category: "Women",
    color: "green",
  },
  {
    id: 12,
    name: "Nike Color Block Swimming Clothes",
    price: 52,
    offPrice: "",
    image: "https://postimg.cc/0bV7K2dy",
    category: "Women",
    color: "black",
  },
  {
    id: 13,
    name: "NikeCourt Dri-FIT Victory Skirt",
    price: 50,
    offPrice: "",
    image: "https://postimg.cc/XrwLG0JH",
    category: "Women",
    color: "turqouise",
  },
  {
    id: 14,
    name: "Nike Pro Dri-FIT Flex Training Shorts",
    price: 65,
    offPrice: "",
    image: "https://postimg.cc/YjJ5KMmj",
    category: "Men",
    color: "green",
  },
  {
    id: 15,
    name: "Nike Therma Training Hoodie",
    price: 69,
    offPrice: "36.97",
    image: "https://postimg.cc/YhyKnYzK",
    category: "Men",
    color: "blue",
  },
  {
    id: 16,
    name: "Nike Therma Training Pants",
    price: 55,
    offPrice: "33.97",
    image: "https://postimg.cc/14JLXwTn",
    category: "Men",
    color: "gray",
  },
  {
    id: 17,
    name: "Air Jordan 1 Mid Shoes",
    price: 100,
    offPrice: "",
    image: "https://postimg.cc/kDVsmSxv",
    category: "Shoes",
    color: "blue",
  },
  {
    id: 18,
    name: "Nike Dri-FIT Ultra Stretch Micro Trunks",
    price: 45,
    offPrice: "36.97",
    image: "https://postimg.cc/nMsyPCr6",
    category: "Men",
    color: "",
  },
  {
    id: 19,
    name: "Nike Sportswear Tech Fleece Pants",
    price: 100,
    offPrice: "",
    image: "https://postimg.cc/KK1XhzQk",
    category: "Women",
    color: "gray",
  },
  {
    id: 20,
    name: "NikeCourt Dri-FIT Pants",
    price: 85,
    offPrice: "",
    image: "https://postimg.cc/PCkzkF4m",
    category: "Women",
    color: "green",
  },
  {
    id: 21,
    name: "Nike Dri-FIT Alate Coverage Bras",
    price: 50,
    offPrice: "",
    image: "https://postimg.cc/bZMbLC5X",
    category: "Women",
    color: "white",
  },
  {
    id: 22,
    name: "Nike Dri-FIT One Luxe Top",
    price: 52,
    offPrice: "",
    image: "https://postimg.cc/t1Nq77Wr",
    category: "Women",
    color: "blue",
  },
  {
    id: 23,
    name: "Nike Tempo Shorts",
    price: 30,
    offPrice: "",
    image: "https://postimg.cc/bsYpFzXb",
    category: "Women",
    color: "pink",
  },
  {
    id: 24,
    name: "Nike Dri-FIT Club Golf Skirt",
    price: 75,
    offPrice: "67.97",
    image: "https://postimg.cc/XrTG9ZZ4",
    category: "Women",
    color: "blue",
  },
  {
    id: 25,
    name: "NikeCourt Dri-FIT Victory Tennis Skirt ",
    price: 60,
    offPrice: "48.97",
    image: "https://postimg.cc/v1t0jdwg",
    category: "Women",
    color: "gray",
  },
  {
    id: 26,
    name: "Jordan Essentials Mesh Shorts",
    price: 55,
    offPrice: "44.97",
    image: "https://postimg.cc/v4ytfSC0",
    category: "Men",
    color: "green",
  },
  {
    id: 27,
    name: "Nike Sportswear Club Fleece Sweater",
    price: 50,
    offPrice: "",
    image: "https://postimg.cc/tZf4Gwhy",
    category: "Men",
    color: "red",
  },
  {
    id: 28,
    name: "Nike Sportswear Club Fleece Joggers",
    price: 55,
    offPrice: "",
    image: "https://postimg.cc/G9VHW8QY",
    category: "Men",
    color: "blue",
  },
  {
    id: 29,
    name: "Nike Dri-FIT ReLuxe Underwear",
    price: 40,
    offPrice: "",
    image: "https://postimg.cc/Hjhprq8C",
    category: "Men",
    color: "gray",
  },
  {
    id: 30,
    name: "Air Jordan 5 Retro Shoes ",
    price: 150,
    offPrice: "",
    image: "https://postimg.cc/HjPN0HtB",
    category: "Shoes",
    color: "gray",
  },
  {
    id: 31,
    name: "Nike Dri-FIT Epic Luxe Pants",
    price: 110,
    offPrice: "88.97",
    image: "https://postimg.cc/GH4mzLn2",
    category: "Women",
    color: "skyblue",
  },
  {
    id: 32,
    name: "Nike Epic Luxe Pants",
    price: 90,
    offPrice: "81.97",
    image: "https://postimg.cc/v13JpnWd",
    category: "Women",
    color: "orange",
  },
  {
    id: 33,
    name: "Nike Air Dri-FIT Swoosh",
    price: 45,
    offPrice: "30.97",
    image: "https://postimg.cc/G4MTt7R8",
    category: "Women",
    color: "purple",
  },
  {
    id: 34,
    name: "Nike Yoga Luxe Tops",
    price: 55,
    offPrice: "",
    image: "https://postimg.cc/DSsjrXCc",
    category: "Women",
    color: "yellow",
  },
  {
    id: 35,
    name: "Nike Sportswear Swoosh Sweater",
    price: 65,
    offPrice: "39.97",
    image: "https://postimg.cc/f3PNVXkf",
    category: "Women",
    color: "orange",
  },
  {
    id: 36,
    name: "Nike Adventure Swimming",
    price: 54,
    offPrice: "",
    image: "https://postimg.cc/7J7STg9v",
    category: "Women",
    color: "red",
  },
  {
    id: 37,
    name: "Nike Club Skirt Golf Skirt",
    price: 70,
    offPrice: "",
    image: "https://postimg.cc/5Q12nL1W",
    category: "Women",
    color: "blue",
  },
  {
    id: 38,
    name: "Nike One Pants",
    price: 50,
    offPrice: "",
    image: "https://postimg.cc/mzkvRrw1",
    category: "Women",
    color: "skyblue",
  },
  {
    id: 39,
    name: "Nike One Luxe Pants",
    price: 90,
    offPrice: "54.97",
    image: "https://postimg.cc/SYzH2tHy",
    category: "Women",
    color: "blue",
  },
  {
    id: 40,
    name: "Nike Yoga Dri-FIT Indy Bras",
    price: 45,
    offPrice: "27.97",
    image: "https://postimg.cc/B8Tz0KHv",
    category: "Women",
    color: "blue",
  },
];

export const users = [
  {
    name: "Saheb mohamadi",
    email: "saheb.ex@gmail.com",
    password: bcrypt.hashSync("12345", 8),
    phoneNumber: "09180000000",
    isAdmin: true,
  },
  {
    name: "John",
    email: "user@example.com",
    password: bcrypt.hashSync("1234", 8),
    isAdmin: false,
    phoneNumber: "09181230000",
  },
];
