const products = [
  {
    id: 1,
    name: "Nike Dri-FIT Trail T-shirt",
    price: "35",
    discount: "",
    offPrice: "",
    type: "T-shirts",
    image: require("./assets/ProductsImages/Nike Dri-FIT Trail T-shirt.webp"),
    category: "Men",
    color: "skyblue",
  },
  {
    id: 2,
    name: "Nike Dri-FIT Training T-shirt",
    price: "85",
    discount: "",
    offPrice: "",
    type: "T-shirts",
    image: require("./assets/ProductsImages/Nike Dri-FIT Training T-shirt.webp"),
    category: "Men",
    color: "blue",
  },
  {
    id: 3,
    name: "Nike Pro Dri-FIT Short-Sleeve Top",
    price: "35",
    discount: "",
    offPrice: "",
    type: "T-shirts",
    image: require("./assets/ProductsImages/Nike Pro Dri-FIT Short-Sleeve Top.webp"),
    category: "Men",
    color: "green",
  },
  {
    id: 4,
    name: "Nike Sportswear Tech Fleece Wash Shorts",
    price: "85",
    discount: "",
    offPrice: "",
    type: "Shorts",
    image: require("./assets/ProductsImages/Nike Sportswear Tech Fleece Wash Shorts.webp"),
    category: "Men",
    color: "blue",
  },
  {
    id: 5,
    name: "Nike Sportswear Essential Sweater",
    price: "65",
    discount: "",
    offPrice: "36.97",
    type: "Sweaters",
    image: require("./assets/ProductsImages/Nike Sportswear Essentials.webp"),
    category: "Women",
    color: "red",
  },
  {
    id: 6,
    name: "Nike Bliss Luxe Pants",
    price: "100",
    discount: "",
    offPrice: "",
    type: "Pants",
    image: require("./assets/ProductsImages/Nike Bliss Luxe.webp"),
    category: "Women",
    color: "black",
  },
  {
    id: 7,
    name: "Nike Dri-FIT Swoosh Bras",
    price: "60",
    discount: "",
    offPrice: "",
    type: "Bras",
    image: require("./assets/ProductsImages/Nike Dri-FIT Swoosh.webp"),
    category: "Women",
    color: "blue",
  },
  {
    id: 8,
    name: "Nike Dri-FIT Top",
    price: "35",
    discount: "",
    offPrice: "",
    type: "T-shirts",
    image: require("./assets/ProductsImages/Nike Dri-FIT.webp"),
    category: "Women",
    color: "pink",
  },
  {
    id: 9,
    name: "Nike Sportswear Gym Vintage",
    price: "35",
    discount: "",
    offPrice: "",
    type: "Shorts",
    image: require("./assets/ProductsImages/Nike Sportswear Gym Vintage.webp"),
    category: "Women",
    color: "gray",
  },
  {
    id: 10,
    name: "Nike Air Max 270 Shoes",
    price: "130",
    discount: "",
    offPrice: "",
    type: "Shoes",
    image: require("./assets/ProductsImages/Nike Air Max 270 Shoes.webp"),
    category: "Shoes",
    color: "black",
  },
  {
    id: 11,
    name: "Nike Sportswear Uphoria Sweater",
    price: "80",
    discount: "",
    offPrice: "",
    type: "Sweater",
    image: require("./assets/ProductsImages/Nike Sportswear Uphoria.webp"),
    category: "Women",
    color: "green",
  },
  {
    id: 12,
    name: "Nike Color Block Swimming Clothes",
    price: "52",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Color Block.webp"),
    category: "Women",
    color: "black",
  },
  {
    id: 13,
    name: "NikeCourt Dri-FIT Victory Skirt",
    price: "50",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/NikeCourt Dri-FIT Victory Skirt.webp"),
    category: "Women",
    color: "turqouise",
  },
  {
    id: 14,
    name: "Nike Pro Dri-FIT Flex Training Shorts",
    price: "65",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Pro Dri-FIT Flex Training Shorts.webp"),
    category: "Men",
    color: "green",
  },
  {
    id: 15,
    name: "Nike Therma Training Hoodie",
    price: "69",
    discount: "",
    offPrice: "36.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Therma Training Hoodie.webp"),
    category: "Men",
    color: "blue",
  },
  {
    id: 16,
    name: "Nike Therma Training Pants",
    price: "55",
    discount: "",
    offPrice: "33.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Therma Training Pants.webp"),
    category: "Men",
    color: "gray",
  },
  {
    id: 17,
    name: "Air Jordan 1 Mid Shoes",
    price: "100",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Air Jordan 1 Mid Shoes.webp"),
    category: "Shoes",
    color: "blue",
  },
  {
    id: 18,
    name: "Nike Dri-FIT Ultra Stretch Micro Trunks",
    price: "45",
    discount: "",
    offPrice: "36.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Dri-FIT Ultra Stretch Micro Trunks.webp"),
    category: "Men",
    color: "",
  },
  {
    id: 19,
    name: "Nike Sportswear Tech Fleece Pants",
    price: "100",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Sportswear Tech Fleece.webp"),
    category: "Women",
    color: "gray",
  },
  {
    id: 20,
    name: "NikeCourt Dri-FIT Pants",
    price: "85",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/NikeCourt Dri-FIT.webp"),
    category: "Women",
    color: "green",
  },
  {
    id: 21,
    name: "Nike Dri-FIT Alate Coverage Bras",
    price: "50",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Dri-FIT Alate Coverage.webp"),
    category: "Women",
    color: "white",
  },
  {
    id: 22,
    name: "Nike Dri-FIT One Luxe Top",
    price: "52",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Dri-FIT One Luxe.webp"),
    category: "Women",
    color: "blue",
  },
  {
    id: 23,
    name: "Nike Tempo Shorts",
    price: "30",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Tempo.webp"),
    category: "Women",
    color: "pink",
  },
  {
    id: 24,
    name: "Nike Dri-FIT Club Golf Skirt",
    price: "75",
    discount: "",
    offPrice: "67.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Dri-FIT Club.webp"),
    category: "Women",
    color: "blue",
  },
  {
    id: 25,
    name: "NikeCourt Dri-FIT Victory Tennis Skirt ",
    price: "60",
    discount: "",
    offPrice: "48.97",
    type: "",
    image: require("./assets/ProductsImages/NikeCourt Dri-FIT Victory Skirt.webp"),
    category: "Women",
    color: "gray",
  },
  {
    id: 26,
    name: "Jordan Essentials Mesh Shorts",
    price: "55",
    discount: "",
    offPrice: "44.97",
    type: "",
    image: require("./assets/ProductsImages/Jordan Essentials Mesh Shorts.webp"),
    category: "Men",
    color: "green",
  },
  {
    id: 27,
    name: "Nike Sportswear Club Fleece Sweater",
    price: "50",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Sportswear Club Fleece.webp"),
    category: "Men",
    color: "red",
  },
  {
    id: 28,
    name: "Nike Sportswear Club Fleece Joggers",
    price: "55",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Sportswear Club Fleece Joggers.webp"),
    category: "Men",
    color: "blue",
  },
  {
    id: 29,
    name: "Nike Dri-FIT ReLuxe Underwear",
    price: "40",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Dri-FIT ReLuxe Boxer Underwear.webp"),
    category: "Men",
    color: "gray",
  },
  {
    id: 30,
    name: "Air Jordan 5 Retro Shoes ",
    price: "150",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Air Jordan 5 Retro Shoes.webp"),
    category: "Shoes",
    color: "gray",
  },
  {
    id: 31,
    name: "Nike Dri-FIT Epic Luxe Pants",
    price: "110",
    discount: "",
    offPrice: "88.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Dri-FIT Epic Luxe.webp"),
    category: "Women",
    color: "skyblue",
  },
  {
    id: 32,
    name: "Nike Epic Luxe Pants",
    price: "90",
    discount: "",
    offPrice: "81.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Epic Luxe.webp"),
    category: "Women",
    color: "orange",
  },
  {
    id: 33,
    name: "Nike Air Dri-FIT Swoosh",
    price: "45",
    discount: "",
    offPrice: "30.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Air Dri-FIT Swoosh.webp"),
    category: "Women",
    color: "purple",
  },
  {
    id: 34,
    name: "Nike Yoga Luxe Tops",
    price: "55",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Yoga Luxe.webp"),
    category: "Women",
    color: "yellow",
  },
  {
    id: 35,
    name: "Nike Sportswear Swoosh Sweater",
    price: "65",
    discount: "",
    offPrice: "39.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Sportswear Swoosh.webp"),
    category: "Women",
    color: "orange",
  },
  {
    id: 36,
    name: "Nike Adventure Swimming",
    price: "54",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Adventure.webp"),
    category: "Women",
    color: "red",
  },
  {
    id: 37,
    name: "Nike Club Skirt Golf Skirt",
    price: "70",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike Club Skirt.webp"),
    category: "Women",
    color: "blue",
  },
  {
    id: 38,
    name: "Nike One Pants",
    price: "50",
    discount: "",
    offPrice: "",
    type: "",
    image: require("./assets/ProductsImages/Nike One.webp"),
    category: "Women",
    color: "skyblue",
  },
  {
    id: 39,
    name: "Nike One Luxe Pants",
    price: "90",
    discount: "",
    offPrice: "54.97",
    type: "",
    image: require("./assets/ProductsImages/Nike One Luxe.webp"),
    category: "Women",
    color: "blue",
  },
  {
    id: 40,
    name: "Nike Yoga Dri-FIT Indy Bras",
    price: "45",
    discount: "",
    offPrice: "27.97",
    type: "",
    image: require("./assets/ProductsImages/Nike Yoga Dri-FIT Indy.webp"),
    category: "Women",
    color: "blue",
  },
];

export default products;

// export const users = [
//   {
//     name: "Saheb mohamadi",
//     email: "saheb.ex@gmail.com",
//     password: bcrypt.hashSync("12345", 8),
//     phoneNumber: "09180000000",
//     isAdmin: true,
//   },
//   {
//     name: "John",
//     email: "user@example.com",
//     password: bcrypt.hashSync("1234", 8),
//     isAdmin: false,
//     phoneNumber: "09181230000",
//   },
// ];
